version: "2"

services:
    # Nginx
    nginx:
        build: ./nginx
        image: wedding/nginx
        volumes:
            - .:/usr/src/app
        links:
            - django
        ports:
            - "80:80"

    # This defines a service for the Django app
    django:
        build: .
        image: wedding/django
        volumes:
            - .:/usr/src/app
        expose:
            - "8000"
        links:
            - postgres
            - redis
        env_file:
            - .django.env
            - .postgres.env

    # This defines a service for the Postgres database
    postgres:
        image: postgres:9.3
        env_file:
            - .postgres.env

    # This defines a service for the Redis database (used as celery broker)
    redis:
        image: redis:latest
